### ISSUE TITLE
Dataset needed

### ISSUE THREAD

**Issue by pskanagaraj** [kavlabs/transfer-learning-for-classification-of-mri-images-as-alzheimer-s-and-parkinson-s#1]
Dear Sir/Madam

Kindly share the details of dataset. 

Thank you.

**Comment by kavlabs** [comment]
yes you can search for ADNI and PPMI datasets

**Comment by pskanagaraj** [comment]
Dear Sir/Madam

I find that in PPMI the images are of .nii format.
Kindly guide me in retrieval of images as you have used in .png format

Thank you.

**Comment by kavlabs** [comment]
you can use any online or offline converter.
I hope this would be helpful: https://github.com/alexlaurence/NIfTI-Image-Converter

**Comment by pskanagaraj** [comment]
Dear author thank you
