### ISSUE TITLE
Help in running of program

### ISSUE THREAD

**Issue by pskanagaraj** [kavlabs/transfer-learning-for-classification-of-mri-images-as-alzheimer-s-and-parkinson-s#2]
Dear author,

I have used 2895 images and the following error occurs 
ValueError                                Traceback (most recent call last)

<ipython-input-30-03dc3ccaa4f0> in <module>()
----> 1 print(confusion_matrix(validation_generator.classes, y_pred))

2 frames

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py in check_consistent_length(*arrays)
    331         raise ValueError(
    332             "Found input variables with inconsistent numbers of samples: %r"
--> 333             % [int(l) for l in lengths]
    334         )
    335 

ValueError: Found input variables with inconsistent numbers of samples: [595, 576]

Kindly do the needful. Thank you.

**Comment by kavlabs** [comment]
did you changed the "totalpics" variable to 2895
